// pages/screening/screening.js
Page({
  data: {
    sex:['不限','男','女'],
    index_sex:0,
    grade:['不限','16级','17级','18级','19级','20级'],
    index_grade:0,
    age:['不限','0-16岁','17-18岁','19-20岁','20-24岁','24岁以上'],
    index_age:0,
    start_date:'2020-12-7',
    end_date:'2020-12-7',
    start_time:"00:00",
    end_time:"23:59",
    duration:['0-30','31-60','61-90','91-120','>120'],
    index_dur:0,
    money:['0-30','31-60','61-90','>90'],
    index_mon:0
  },
  changeSex(e){
    this.setData({
      index_sex:e.detail.value
    })
  },
  changeGrade(e){
    this.setData({
      index_grade:e.detail.value
    })
  },
  changeAge(e){
    this.setData({
      index_age:e.detail.value
    })
  },
  startDateChange(e){
    this.setData({
      start_date:e.detail.value
    })
  },
  endDateChange(e){
    this.setData({
      end_date:e.detail.value
    })
  },
  startTimeChange(e){
    this.setData({
      start_time:e.detail.value
    })
  },
  endTimeChange(e){
    this.setData({
      end_time:e.detail.value
    })
  },
  durationChange(e){
    this.setData({
      index_dur:e.detail.value
    })
  },
  moneyChange(e){
    this.setData({
      index_mon:e.detail.value
    })
  },
  return:function(){
    wx.navigateBack({
      delta:1
    })
  }
})